### PR TITLE
merge with http-random-access

### PR DESCRIPTION
**Pull request by e-e-e**
@bcomnes this is a merge of our two http interfaces - do you want to have a look over and let me know what you think.

This will close these issues:
https://github.com/random-access-storage/random-access-http/issues/15
https://github.com/random-access-storage/random-access-http/issues/11

### CODE REVIEW

**Comment by bcomnes** [comment]
Do you see any advantages to one or the other?

**Comment by e-e-e** [comment]
For me the main thing that the current implementation misses is the ability to use relative file paths from a base path. Without this its not possible to use as a drop in replacement for dat storage.

The other advantage of this implementation would be that it should be usable in the browser too - as its using axios rather than node by default.

Other than those our implementations are pretty similar.

**Comment by e-e-e** [comment]
I originally wrote my implementation for this - https://github.com/e-e-e/dat-http-proxy.

**Comment by bcomnes** [comment]
Want to just merge the repos replacing my older implementation with yours and keep the more consistent random-access-http name?

**Comment by e-e-e** [comment]
That was my original thought - but actually i ended up grabbing details from yours for this branch too. All the checks on content-length are from your implementation.

**Comment by e-e-e** [comment]
I feel like this branch is the combination of both of our work - is there anything you see missing?

**Comment by bcomnes** [comment]
I'll let you merge when ready

**Comment by e-e-e** [comment]
Awesome @bcomnes thanks. I will do a major version bump and publish shortly.

**Pull request merged**
